spring:
  application:
    name: movie-rank
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/mydatabase
    username: myuser
    password: secret